name: CI/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and execute tests with Maven
      run: mvn -B package

    - name: Deploy with Render
      if: success()
      run : |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

